version: '3.8'

networks:
  mentoranetwork:
    driver: bridge

services:

#service for postgres db
  postgres:
    image: postgres
    container_name: mentora_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    networks:
      - mentoranetwork

 # service for pgadmin to interact with posthres  using GUI
  pgadmin:
    image: dpage/pgadmin4
    container_name: mentora_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5054:80"

    networks:
      - mentoranetwork
    depends_on:
      - postgres

#  service for api testing
  # mentora_api:
  #   build: .
  #   container_name: mentora_api
  #   command: uvicorn main:app --host 0.0.0.0 --port 8400 --reload
  #   ports:
  #     - "8400:8400"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - mentoranetwork

