version: '3.8'

networks:
  mentoranetwork:
    driver: bridge

services:
  postgres:
    image: postgres
    container_name: mentora_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "8000:5432"

    networks:
      - mentoranetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: mentora_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5054:80"

    networks:
      - mentoranetwork
    depends_on:
      - postgres

